### ISSUE TITLE
Followed the tutorial for this, to no avail... is it up to date?

### ISSUE THREAD

**Issue by saminightshift** [bakerframework/baker-android#109]
Trying to build a standalone Android app from a Baker project, already done our iOS one but can't seem to get the Android one to work.

Followed the tutorial to the letter but I'm unable to effectively build the app. (Granted I am an iOS user and Android isn't something I'm used to but shouldn't be this difficult!)

So my question is, is the tutorial up to date? Had to botch a few things in the iOS tutorial so am thinking it's not 100% ?

**Comment by fcontreras** [comment]
Hey unfortunately the tutorial is no up to date. Sorry

**Comment by shutterflypro** [comment]
@saminightshift Did you get this to work??
