### ISSUE TITLE
Video, Photo Gallery and web link

### ISSUE THREAD

**Issue by ulixcat** [bakerframework/baker-android#71]
I have a hpub of magazine with some link (video, Photo gallery, Web pages...
In all html files these link are "?referrer=baker" and with the iOS version of Baker App working properly
They open in the page, and the button appears in the toolbar to close them remaining into the page

With Android Baker do not work well. because it is impossible to close them without leaving the issue
And there is not a button to return

Any idea to solve this problem?

**Comment by corsa** [comment]
I know this thread is almost a year old, but I just installed the latest version of ABaker and had the same problem -- "?referrer=baker" links opened in a modal web view on iOS Baker, but on ABaker it just replaced my internal page, and there was no way to navigate out of it.

I discovered that unlike in iOS Baker, case matters. So when I changed it to "?referrer=Baker" it started working in ABaker, the external link appeared in a pop-up web view, with an "X" close widget on it.

Unfortunately, the pop up web view in ABaker lacks any sort of navigation controls, so once you are on an external link and clicking around, you can't go "back" within the external website, or refresh it, or anything like that. But at least you can close the web view and get back to your original page in your Book.

It would be great if the pop up ABaker web view had navigation controls added to it at some point.

Hope this helps.
