### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by makeclan** [bakerframework/baker-android#82]
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':ABaker'.
  
  > Could not resolve all dependencies for configuration ':ABaker:_debugCompile'.
  > Could not find com.google.android.gms:play-services:6.5.85.
  >  Searched in the following locations:
  >      http://dl.bintray.com/populov/maven/com/google/android/gms/play-services/6.5.85/play-services-6.5.85.pom
  >      http://dl.bintray.com/populov/maven/com/google/android/gms/play-services/6.5.85/play-services-6.5.85.jar
  >      https://repo1.maven.org/maven2/com/google/android/gms/play-services/6.5.85/play-services-6.5.85.pom
  >      https://repo1.maven.org/maven2/com/google/android/gms/play-services/6.5.85/play-services-6.5.85.jar
  >      file:/Users/lhf/.m2/repository/com/google/android/gms/play-services/6.5.85/play-services-6.5.85.pom
  >      file:/Users/lhf/.m2/repository/com/google/android/gms/play-services/6.5.85/play-services-6.5.85.jar
  >  Required by:
  >      com.baker:ABaker:1.1
  > Could not find com.android.support:support-v4:21.0.3.
  >  Searched in the following locations:
  >      http://dl.bintray.com/populov/maven/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
  >      http://dl.bintray.com/populov/maven/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
  >      https://repo1.maven.org/maven2/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
  >      file:/Users/lhf/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.pom
  >      file:/Users/lhf/.m2/repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.jar
  >  Required by:
  >      com.baker:ABaker:1.1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 53.076 secs

**Comment by fcontreras** [comment]
You seems to be missing the google play libraries make sure you have them all installed as proposed in the wiki.
https://github.com/bakerframework/baker-android/wiki/Testing-Baker-Android
