### ISSUE TITLE
Error parsing the document

### ISSUE THREAD

**Issue by airterjun** [bakerframework/baker-android#84]
Hello @fcontreras and baker android team 

I'm using the latest baker android and run as standalone mode, it's working but I got an error parsing the document, all the file is there on book folder, please see the attached image for the error LOG and the book folder files

![screen shot 2015-01-23 at 4 17 29 pm](https://cloud.githubusercontent.com/assets/24951/5871676/1d11e7d0-a31c-11e4-87ec-af044ee52053.png)

![screen shot 2015-01-23 at 4 23 35 pm](https://cloud.githubusercontent.com/assets/24951/5871684/3a5a7a78-a31c-11e4-9b9e-a3d086108bb1.png)

and I wondering why the book name showing double, please see the picture at line `.../android_asset/books/bfvbfv/page_contents_villas.html: open failed: ENOENT (No such file or directory...`

and please check picture from where I got the name double
![screen shot 2015-01-23 at 4 29 17 pm](https://cloud.githubusercontent.com/assets/24951/5871756/080cf2a2-a31d-11e4-9dad-f9c3703bdbe4.png)

The `finalPath` is already included `book.getMagazineName()`

```
  if (STANDALONE_MODE) {
        boolean fromAssets = !this.getResources().getBoolean(R.bool.sa_read_from_custom_directory);
        if (fromAssets) {
            path = "file:///android_asset"
                    .concat(File.separator)
                    .concat(getString(R.string.sa_books_directory))
                    .concat(File.separator)
                    .concat(book.getMagazineName());
        }

   } else if (ENABLE_TUTORIAL) {
        path = "file:///android_asset"
                .concat(File.separator)
                .concat("abaker_usage");
    }

    if (book.getLiveUrl() != null) {
        path = book.getLiveUrl();
    }
    final String finalPath = path;
```

and why `book.getMagazineName()` again add in `String page = finalPath + book.getMagazineName() + File.separator + book.getContents().get(position)` ?

Ahh... and one more question, how I use `-baker-vertical-pagination` vertical swipe like on iOs version, is android baker not support yet?? I tried look at bookJason class there no included yet for option `-baker-vertical-pagination`, is there any plugin for support the vertical swipe??  

Please help me to fix it, because baker awesome framework :) 

Any comments, help and suggest is welcome :)

Thanks

**Comment by fcontreras** [comment]
Hi, 
As you said the book path is already included in the finalPath.. try just removing it.
On the other hand.. yes vertical pagination is not yet supported sorry for that.
