### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by Mazzy71** [bakerframework/baker-android#85]
Is there any solution for autoplay in Android Baker? I know that there is a way in iOS, where you have to mess with IndexViewController.m file; have we got something similar in Anroid?

Thanks!;)

**Comment by ijerez2001** [comment]
I use javascript to do a html video tag autoplay.

**Comment by Mazzy71** [comment]
How You do it? I've tried with play(); in 
window.addEventListener("focus", function() {}, true); 
but it doesn't work..

**Comment by ijerez2001** [comment]
Your code only work with you swipe to another page, but when the page is the first or when the page is loaded from index.html, you have to call javascript function from Android code:

``` java
webview.setWebViewClient(new WebViewClient() {
    // autoplay when finished loading via javascript injection
    public void onPageFinished(WebView view, String url) { 
        webview.loadUrl("javascript:(function() { document.getElementById('videotagid').play(); })()");
    }
}); 
```

I use a own css class to identify autoplay videos and my function do something like this:

``` java
webview.loadUrl("javascript:(function() { $('.autoplay')[0].play(); })()");
```
