### ISSUE TITLE
Error when installing the gradlew

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android#86]
I am trying to run the ./gradlew install but I am getting this error
![screen shot 2015-02-05 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/5607372/6072995/31c2bca4-ad5d-11e4-8235-f404a8e02528.png)

What do I need to do?

**Comment by codegeek511** [comment]
@fcontreras Have you had a chance to look into this?

**Comment by fcontreras** [comment]
Hi, 

Make sure you have downloaded the Android SDK.
Once you are done with it, on your project create a file named local.properties must be at the same level of the griddle.bat and gradlew file.

On that file, write a line like this one
sdk.dir=[your path to the sdk]

And try again.

**Comment by codegeek511** [comment]
@fcontreras Thanks that helped! I also had to move the ABakerProject out of the the folder it comes in when you download it and put it into first level of the Android Projects folder. Its all good now. :)

**Comment by fcontreras** [comment]
Glad to know it helped... Im closing this one. 
Regards
