### ISSUE TITLE
Error package R does not esist

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android#87]
![screen shot 2015-02-24 at 4 58 41 pm](https://cloud.githubusercontent.com/assets/5607372/6362882/6dffc912-bc46-11e4-8974-25cc5a8d7faa.png)

Not sure what went wrong here, any reason why I have these errors?

**Comment by tobiasstrebitzer** [comment]
Once in a while we stumble upon this problem:
- Restarting android studio might help.
- Using terminal / bash in your project root directory, run `./gradlew --stop` (it will automatically start again)

**Comment by codegeek511** [comment]
@tobiasstrebitzer neither of those worked, I still have the same 4 errors.

**Comment by codegeek511** [comment]
@tobiasstrebitzer Any other things I could try? Still having the same issue.

**Comment by tobiasstrebitzer** [comment]
Hi @codegeek511, can you try using the https://github.com/bakerframework/baker-android-refactor repository, as a fresh installation. We haven't encountered the problem there.

**Comment by codegeek511** [comment]
@tobiasstrebitzer I can.....why is their two repositories? Whats the difference between them?

**Comment by codegeek511** [comment]
@tobiasstrebitzer When I try to run the "./gradlew install" command I get back 
![screen shot 2015-03-17 at 5 46 01 pm](https://cloud.githubusercontent.com/assets/5607372/6700590/84dfe31e-cccd-11e4-9a14-a94c9fb9e84c.png)

**Comment by fcontreras** [comment]
This error is common and most time refers to a import of the R library.
Try removing it if you are still having the issue.

**Comment by codegeek511** [comment]
@fcontreras where is the R library?

**Comment by fcontreras** [comment]
Hi, should be in your imports in the issued file

**Comment by codegeek511** [comment]
@fcontreras Sorry I don't know what that means. To be clear, you aren't talking about the SDK manager are you?

**Comment by codegeek511** [comment]
@tobiasstrebitzer @fcontreras So I just ran it again and it worked, not sure if I actually did something to fix it....but the new project has ran
