### ISSUE TITLE
Does anyone have an app up for Android yet?

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/baker-android#88]
I would like to look at it and see how it behaves etc. on the android os. Thanks.

**Comment by tobiasstrebitzer** [comment]
Hi @codegeek511,

we have three fresh magazines on play store, released last week:
[High Voltage Magazine](https://play.google.com/store/apps/details?id=com.highvoltage.highvoltage&hl=en), [Soccer - Life OFF The Pitch](https://play.google.com/store/apps/details?id=com.soccertraining.magazine&hl=en) and [Press Perspectives](https://play.google.com/store/apps/details?id=com.freeportpress.pressperspectives&hl=en).

They are based on the latest version of [Baker Android Refactor](https://github.com/bakerframework/baker-android-refactor).

I wouldn't mind if you'd leave a review ;-)

Cheers,
Toby

**Comment by ijerez2001** [comment]
Hi @codegeek511,

We have two magazines based on Baker Android with some customs.
They are in Spanish and English/Spanish:
- [TopPadel 360](https://play.google.com/store/apps/details?id=com.toppadel.quiosco)
- [5 Senses Wine](https://play.google.com/store/apps/details?id=com.fivesw.quiosco)

Cheers
Iván

**Comment by codegeek511** [comment]
@tobiasstrebitzer They look awesome! How did you get paid items though I thought that wasn't implemented yet?

**Comment by fcontreras** [comment]
Hey @codegeek511 there is a version of this repo that is not yet stable but has implemented in app purchases, take a look at baker android refactor
