### ISSUE TITLE
Internal links… page missing

### ISSUE THREAD

**Issue by webcarp** [bakerframework/baker-android#90]
Hello.
I have a recurrent problem with the internal links…When I press them, the magazine shows to me the page I want. But…when I want return to the page where the link must be…This page are missing! In her place it's appears the page info.html in a down layer (this page is blocked and the swipe not run for her).
Thanks in advance for support, best regards

**Comment by fcontreras** [comment]
Hey Gabriel.. 
can you post part of the code you use for internal links, and a bit more details on how are you trying to go back.

Regards

**Comment by webcarp** [comment]
Hello.
You can see the error: https://youtu.be/4Sxp4jY6Mtc
The code: 
a href="5-nota-editor.html"><h3>Edito</h3></a

**Comment by fcontreras** [comment]
thats odd.. is it reproducible in another device?

**Comment by webcarp** [comment]
This recurrent malfunctioning it's happens in every device. 
The only way for I can see this page is to swip a lot go ahead and return the swipes to back again

**Comment by fcontreras** [comment]
ok.. I'll add this as a bug.. since that is not suppose to happen, please keep in loop since we will need to reproduce it and may be asking couple of questions.
Thanks for your help.

**Comment by Jotalele** [comment]
Hi, I also am having a heck of a time with exactly this problem. I just can't find a way around it. Are there any developments on this?
Thanks and all the best,
Jon

**Comment by webcarp** [comment]
Hello.
Just I wanted to know if there is any progress in this area.
Thank you.

**Comment by felagund18** [comment]
Will this bug be considered to be fixed?
