### ISSUE TITLE
Debug error while runing app

### ISSUE THREAD

**Issue by proecorp** [bakerframework/baker-android#97]
Hi,
Android Studio (v. 1.2.2) is showing this msg when I try to run the app.

/Users/Elias/Documents/SpeakupDigital/baker-android-master/RevistaSpeakUpDigtial/app/build/intermediates/res/debug/drawable-hdpi-v4/abaker_button.xml: error: Duplicate file.
/Users/Elias/Documents/SpeakupDigital/baker-android-master/RevistaSpeakUpDigtial/app/build/intermediates/res/debug/drawable-hdpi/abaker_button.xml: Original is here. The version qualifier may be implied.
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/Elias/Library/Android/sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

Does anyone know how to fix this error ?

**Comment by Jotalele** [comment]
Hi, Im no programmer, and have been feeling my way through this, but I think I experienced the same problem and solved it by changing the 'buildToolsVersion' in the build.gradle file for the app to a different one that was loaded in Android SDK Manager. In this case "20" worked.
