### ISSUE TITLE
Drag N Drop and Scrolling

### ISSUE THREAD

**Issue by cescc78** [bakerframework/baker-android#99]
Hi first thanks for the migration of the Baker Framework it works really great. 

Recently I make a book with some interactions and scrollable frames, on iOS Baker runs great but on Android all the "dragable" elements if the interaction is horizontal, it's swipe the page, the interaction needs to be done diagonal to gorks.

Is there any way to fix this.

Regards.

**Comment by fcontreras** [comment]
Hi, unfortunately there is no fix for that right now since that was
identified as an issue with the Android WebView.

**Comment by cescc78** [comment]
Thx for your answer Francisco and this grear proyect.

I hope this can be fixed in a future release.
